name: Build Release APK

on:
  push:
    branches: ["main"]
    paths-ignore:
      - '**.md'
      - 'fastlane/**'
      - '.github/workflows/crowdin_contributors.yml'
  workflow_dispatch: {}

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Signing info
  IDE_SIGNING_ALIAS: ${{ secrets.IDE_SIGNING_ALIAS }}
  IDE_SIGNING_AUTH_PASS: ${{ secrets.IDE_SIGNING_AUTH_PASS }}
  IDE_SIGNING_AUTH_USER: ${{ secrets.IDE_SIGNING_AUTH_USER }}
  IDE_SIGNING_KEY_PASS: ${{ secrets.IDE_SIGNING_KEY_PASS }}
  IDE_SIGNING_STORE_PASS: ${{ secrets.IDE_SIGNING_STORE_PASS }}
  IDE_SIGNING_URL: ${{ secrets.IDE_SIGNING_URL }}
  IDE_SIGNING_KEY_BIN: ${{ secrets.IDE_SIGNING_KEY_BIN }}

  # Build configuration
  BUILD_JAVA_VERSION: '17'
  BUILD_JAVA_DIST: 'adopt'

jobs:
  build_apk:
    name: Build Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.BUILD_JAVA_VERSION }}
          distribution: ${{ env.BUILD_JAVA_DIST }}

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build release APK
        run: ./gradlew :core:app:assembleRelease

      - name: Copy release APKs
        run: |
          cp core/app/build/outputs/apk/release/app-arm64-v8a-release-unsigned.apk ./

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: release-apks
          path: app-arm64-v8a-release-unsigned.apk
