name: Build Release APK
permissions:
  actions: write
  contents: read
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

env:
  BUILD_JAVA_VERSION: '17'
  BUILD_JAVA_DIST: 'adopt'

jobs:
  build_release_apk:
    name: Build Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.BUILD_JAVA_VERSION }}
          distribution: ${{ env.BUILD_JAVA_DIST }}

      - name: Change Gradle wrapper permissions
        run: chmod +x ./gradlew

      - name: Restore Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Assemble Release APK
        run: ./gradlew :core:app:assembleRelease

      - name: Copy APKs
        run: |
          cp core/app/build/outputs/apk/release/app-arm64-v8a-release.apk ./ || true
          cp core/app/build/outputs/apk/release/app-armeabi-v7a-release.apk ./ || true
          cp core/app/build/outputs/apk/release/app-x86_64-release.apk ./ || true

      - name: Upload APK arm64-v8a
        uses: actions/upload-artifact@v4
        with:
          name: apk-arm64-v8a-release
          path: app-arm64-v8a-release.apk

      - name: Upload APK armeabi-v7a
        uses: actions/upload-artifact@v4
        with:
          name: apk-armeabi-v7a-release
          path: app-armeabi-v7a-release.apk

      - name: Upload APK x86_64
        uses: actions/upload-artifact@v4
        with:
          name: apk-x86_64-release
          path: app-x86_64-release.apk

      - name: Upload Proguard Mappings (optional)
        uses: actions/upload-artifact@v4
        with:
          name: release-mappings
          path: '**/build/outputs/mapping'
